development:
  APP_ID: '113436499370506'
  ACCESS_TOKEN: 'EAABnK34ZC4goBAKAQ37FbVAylUIjQ9a9YKJlQra21jorCViVoiV6UsccZCYNwtvK8ETfJ0rEnuf68ZAv7zg8AEeI8DQU8ZAOywO2Ituu8oVvcan9XFYsI215ukJZBINlIGfH3FwZAT9JvgADtQy664cZCGyd2mxsFeUyn8ls6JIMe60anGLIAGL'
  STAGING_ACCESS_TOKEN: 'EAAaM60daeZAoBAHZBZBGZC0mSHoXxqEOAkda4eDAfA9qUwgKy9reQMO5nYG5DdhZAyHy1lVB9ed6aETzhuZC0DJa3AwhUy5JRu8kZAETXNP1476rz79fnhJazGiAW7ZAlvKPcYHsZBQCDBFcK4ns9AkXu1qZAtIg5EAZCtZBdb0HoIcjU1dZANPlZCZAucE'
  PRODUCTION_ACCESS_TOKEN: 'EAAbEr7dz6gYBAPx7lzAejiZArjcAvJRUdeLkeiPmZAmZBL6W5L2cdQiXCRf0Q6huEDPNDmypTZAGH5J0AwZBqVnx7MkmeD86FUqC6TSV2V7whSx62Sz3KWsjyNOSLZCFCFRadpjiZCxcbuX0JhWeckbnZC8enyNbuodWzIptElBh3HmqIDUVPYBq'
  APP_SECRET: '7feab229f317ab03732cdee9f7ceda4d'
  VERIFY_TOKEN: 'Love'
  PAGE_ID: '128176767815605'
  ROOT_URL: 'https://11b1da38.ngrok.io'
  TEST_IMG_URL: 'https://i.imgur.com/bqcJBOc.jpg'
  LUIS_ID: '4eac9c01-56b7-49b0-a568-4ea6eea47ddb'
  LUIS_KEY: 'be3a31f8ab0b469ebaa4852d1cc5e6d4'
  GOOGLE_MAP_KEY: 'AIzaSyAYQigrTA4AuiQMFKxylgPpy_yi07_Vo2U'
  GOOGLE_PLACE_KEY: 'AIzaSyBk4WDsiTW8Zkz0azrnG-tKQpGVszjhT8Q'
  TBOT_HOME_PAGE: 'https://tt.house/'
  PROPERTY_HOME_PAGE: 'https://property.tt.house/'
  CHAT_BOX_ID: '263902037430900'
  line_channel_secret: '95d0e1dc1b3b92376668e987bed5678d'
  line_channel_token: 'M7WgyEDO/0Fyl0Nu26pqcvlEXH3u9NofA50hWJ1XxmUHfN+JUPB9mx5Uej/wEhTcGH+/QVl3tDkDqzGsu3B5JvExyW8YpiLJhqeMNQ1hLzj0IHt5RfmL5UTQdRA8jujzgcX0CH5v+g5r2y6MvvhVMQdB04t89/1O/w1cDnyilFU='

  
test:
  APP_ID: '113436499370506'
  ACCESS_TOKEN: 'EAABnK34ZC4goBAKAQ37FbVAylUIjQ9a9YKJlQra21jorCViVoiV6UsccZCYNwtvK8ETfJ0rEnuf68ZAv7zg8AEeI8DQU8ZAOywO2Ituu8oVvcan9XFYsI215ukJZBINlIGfH3FwZAT9JvgADtQy664cZCGyd2mxsFeUyn8ls6JIMe60anGLIAGL'
  APP_SECRET: '7feab229f317ab03732cdee9f7ceda4d'
  VERIFY_TOKEN: 'Love'
  PAGE_ID: '128176767815605'
  ROOT_URL: 'https://11b1da38.ngrok.io'
  TEST_IMG_URL: 'https://i.imgur.com/bqcJBOc.jpg'
  LUIS_ID: '4eac9c01-56b7-49b0-a568-4ea6eea47ddb'
  LUIS_KEY: 'be3a31f8ab0b469ebaa4852d1cc5e6d4'
  GOOGLE_MAP_KEY: 'AIzaSyAYQigrTA4AuiQMFKxylgPpy_yi07_Vo2U'
  GOOGLE_PLACE_KEY: 'AIzaSyBk4WDsiTW8Zkz0azrnG-tKQpGVszjhT8Q'
  TBOT_HOME_PAGE: 'https://property.tt.house/'
  PROPERTY_HOME_PAGE: 'https://property.tt.house/'
  CHAT_BOX_ID: '263902037430900'

staging:
  APP_ID: '1843792002578842'
  ACCESS_TOKEN: 'EAAaM60daeZAoBAHZBZBGZC0mSHoXxqEOAkda4eDAfA9qUwgKy9reQMO5nYG5DdhZAyHy1lVB9ed6aETzhuZC0DJa3AwhUy5JRu8kZAETXNP1476rz79fnhJazGiAW7ZAlvKPcYHsZBQCDBFcK4ns9AkXu1qZAtIg5EAZCtZBdb0HoIcjU1dZANPlZCZAucE'
  APP_SECRET: 'cafae06ec50682cac0568d23ad802b67'
  VERIFY_TOKEN: 'Love'
  PAGE_ID: '312489975893032'
  ROOT_URL: 'https://fbotest.tt.house'
  ROOT_WSS_URL: 'sx://fbotest.tt.house/cable'
  TEST_IMG_URL: 'https://i.imgur.com/bqcJBOc.jpg'
  LUIS_ID: 'a69a4625-275f-412e-9967-e33481659d3d'
  LUIS_KEY: 'be3a31f8ab0b469ebaa4852d1cc5e6d4'
  GOOGLE_MAP_KEY: 'AIzaSyAYQigrTA4AuiQMFKxylgPpy_yi07_Vo2U'
  GOOGLE_PLACE_KEY: 'AIzaSyBk4WDsiTW8Zkz0azrnG-tKQpGVszjhT8Q'
  RDS_DB_NAME: 'fb_ttuibot'
  RDS_USERNAME: 'fb_bot'
  RDS_PASSWORD: '1qaz2wsx'
  RDS_HOSTNAME: 'ec2-107-23-249-87.compute-1.amazonaws.com'
  RDS_PORT: '3306'
  TBOT_HOME_PAGE: 'https://property.tt.house/'
  PROPERTY_HOME_PAGE: 'https://property.tt.house/'
  CHAT_BOX_ID: '263902037430900'

production:
  APP_ID: '1905108836411910'
  ACCESS_TOKEN: 'EAAbEr7dz6gYBAPx7lzAejiZArjcAvJRUdeLkeiPmZAmZBL6W5L2cdQiXCRf0Q6huEDPNDmypTZAGH5J0AwZBqVnx7MkmeD86FUqC6TSV2V7whSx62Sz3KWsjyNOSLZCFCFRadpjiZCxcbuX0JhWeckbnZC8enyNbuodWzIptElBh3HmqIDUVPYBq'
  APP_SECRET: '6c3039d335b333cec706dba49176227f'
  VERIFY_TOKEN: 'Love'
  PAGE_ID: '1889885754385267'
  ROOT_URL: 'https://kerker.herokuapp.com'
  ROOT_WSS_URL: 'ws://tbot-fb.tt.house/cable'
  TEST_IMG_URL: 'https://tbot-fb.tt.house'
  LUIS_ID: '3a26f410-6896-4189-ae1c-1ed6272f4108'
  LUIS_KEY: 'be3a31f8ab0b469ebaa4852d1cc5e6d4'
  GOOGLE_MAP_KEY: 'AIzaSyAYQigrTA4AuiQMFKxylgPpy_yi07_Vo2U'
  GOOGLE_PLACE_KEY: 'AIzaSyBk4WDsiTW8Zkz0azrnG-tKQpGVszjhT8Q'
  RDS_DB_NAME: 'fb_bot'
  RDS_USERNAME: 'fb_bot'
  RDS_PASSWORD: '1qaz2wsx'
  RDS_HOSTNAME: 'ec2-34-226-201-47.compute-1.amazonaws.com'
  RDS_PORT: '3306'
  TBOT_HOME_PAGE: 'https://property.tt.house/'
  PROPERTY_HOME_PAGE: 'https://property.tt.house/'
  
